#!/data/data/com.termux/files/usr/bin/python3

from Dev_calc2 import *

root = Tk()
root.title('Dev_calc')

coord = Coord(root, height = 500, width = 500, bg = 'ivory')
coord.grid(row = 1, column = 1, columnspan = 3)
Label(root, text = 'Enter a m argument: ').grid(row = 2, column = 1)
entree = Entry(root)
entree.grid(row = 2, column = 2)
Label(root, text = 'Enter a p argument: ').grid(row = 3, column = 1)
entree2 = Entry(root)
entree2.grid(row = 3, column = 2)
bu1 = Button(root, 
             text = 'Draw', 
             width = 20, 
             command = lambda: eval('coord.equation_1(%s, %s)' % ( entree.get(), entree2.get() ))
        )
bu1.grid(row = 2, column = 3)
bu2 = Button(root,
                text = 'Delete',
                width = 20,
                command = coord.my_delete
             )
bu2.grid(row = 3, column = 3)
root.mainloop()
